prefix = '?' # Prefix for all commands
guild_id = 704732292328980591 # Required - ID of guild
log_channel_id = -1 # Server channel to log commands to, use -1 to disable it

[economy]
enabled = true
format = '${VAL}.00' # Format for all of economy. Use `{VAL}` for the number EX: '£{VAL}.00' will format as £100.00
split_nums = true # Whether or not to split numbers with commas EX: 25,000
